language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypi"
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9.9
  - DJANGO_VERSION=1.8.9

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script: nosetests
